name: expense_manager_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  http: ^1.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/Svg/
